name: PR Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_target:
    types: [closed]

jobs:
  handle-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Call External API on PR Opened/Updated/Reopened
      if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened')
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        response=$(curl --write-out "%{http_code}" --silent --output /dev/null -H "Authorization: ApiKey ${{ secrets.DBT_TOKEN }}" "https://devdbt.5x.co/jobs/v1/56fbb6a7-0d09-40d8-91f9-3f67734d731d/jobs/ci/$PR_NUMBER/run")
        echo "API Response Code: $response"
        if [ "$response" -ne 200 ]; then
          echo "::error::API check failed with response code $response"
          exit 1
    - name: Handle PR Draft
      if: github.event_name == 'pull_request' && github.event.action == 'ready_for_review'
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        curl --write-out "%{http_code}" --silent --output /dev/null -H "Authorization: ApiKey ${{ secrets.DBT_TOKEN }}" "https://devdbt.5x.co/jobs/v1/56fbb6a7-0d09-40d8-91f9-3f67734d731d/jobs/ci/$PR_NUMBER/run"
    - name: Handle PR Merge
      if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        curl --location --request DELETE "https://devdbt.5x.co/jobs/v1/56fbb6a7-0d09-40d8-91f9-3f67734d731d/jobs/ci/$PR_NUMBER" --header "Authorization: ApiKey ${{ secrets.DBT_TOKEN }}"
    - name: Handle PR Closure Without Merge
      if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == false
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        echo "PR #$PR_NUMBER closed without merge"
