version: 2

sources:
  - name: tpch
    database: your_database_name
    schema: your_schema_name  # This might be 'public' or another schema where your TPC-H tables are located.
    tables:
      - name: customer
      - name: orders
      - name: lineitem
      - name: part
      - name: supplier
      - name: partsupp
      - name: nation
      - name: region
